<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="author" content="Luna BURATTI-FAYOLLE">
    <title>Portfolio - Luna BURATTI-FAYOLLE</title>
    <link rel="stylesheet" href="css/style.css" type="text/css" >
    <link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css" type="text/css" >
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <link rel="icon" type="image/x-icon" href="imgs/favicon-48x48.png" >
</head>
<body>
    
<!--

- réduire la boite taille de la boite de compétences
- drapeau à côté du texte langue correspondant à la langue sélectionnée
- btn pour revenir en haut de la page dans la nav ?
- Texte sous les icônes
- remplacer thèmes par une icone accessibilité et y ranger thèmes dedans
- permettre de diminuer/augmenter la taille de la police
- rajouter les centres d'interêts
- le rendre responsive (mobile et tablette)
- faire en sorte que le thème sélectionné reste même après avoir quitté le site
- changer le margin bottom du btn de la boite de texte

-->
    
    <nav>
        <div id="space-between">
            <div class="d-flex">
                <div class="dropdown-menu">
                    <a href="#" class="drop-link"><?= __('Langue') ?></a>
                    <div class="dropdown-content">
                        <a href="index.php?lang=fr" class="lang-change"><img src="imgs/flags/france-flag.png" alt="France flag" class="flag">Français</a>
                        <a href="index.php?lang=en" class="lang-change"><img src="imgs/flags/uk-flag.png" alt="UK flag" class="flag">English</a>
                    </div>
                </div>
                
                <div class="dropdown-menu">
                    <a href="#" class="drop-link"><?= __('Thème') ?></a>
                    <div id="themes">
                        <button id="change-theme-btn">
                            <i class="fa-solid fa-moon"></i>
                            <i class="fa-solid fa-sun"></i>
                        </button>
                        <p id="themes-p"><?= __('Cliquez pour changer de thème') ?></p>
                    </div>
                </div>
            </div>
            
            <ul class="d-flex">
                <li><a href="#projects"><?= __('Projets')?></a></li>
                <li><a href="#competences"><?= __('Compétences')?></a></li>
                <li><a href="#contact"><?= __('Contact')?></a></li>
            </ul>
        </div>
    </nav>
    
    <header class="d-flex">
        <div id="header">
            <h1><?= __('Bonjour, je m’appelle')?> <span>Luna</span> <?= __('et je suis une jeune')?> <span><?= __('développeuse web')?></span> <?= __('de 19 ans.')?></h1>
            <h2><?= __('Je recherche une')?> <span><?= __('opportunité en alternance')?></span> <?= __('pour devenir une développeuse full stack confirmée.')?></h2>
        </div>
    </header>
    
    <main class="container" id="accueil">
        
        <section class="home d-flex">
            
            <div class="d-flex" id="profile">
                <img src="imgs/Photo_CV_30092024.jpg" id="profile-img" alt="Ma photo">
    
                <p id="find-me"><?= __('Vous pouvez me retrouver sur :')?></p>
                <article class="d-flex" id="socials-icons">
                    <a href="https://github.com/Luna-bf" target="_blank" class="fa-brands fa-github"></a>
                    <a href="https://www.linkedin.com/in/luna-buratti-fayolle/" target="_blank" class="fa-brands fa-linkedin"></a>
                </article>
            </div>
            
            <article id="searching-for">
                <h2><?= __('Qui suis-je ?')?></h2>
                <br>
                <p><?= __('Actuellement en recherche à la 3W Academy, je suis une jeune développeuse web junior de 19 ans passionnée par le développement et la création de solutions innovantes. Dans l’optique d’évoluer dans ce domaine, je suis en quête d\'une opportunité d’apprentissage en alternance pour mettre en pratique mes compétences et apprendre auprès de professionnels expérimentés.')?></p>
                <br>
                <p><?= __('Motivation, curiosité et persévérance sont des soft skills qui me représentent et bien que je sois au début de mon parcours, je suis déterminée à monter en compétences aussi bien front-end qu’en back-end afin de devenir une développeuse full-stack confirmée. Je possède déjà des connaissances en HTML, CSS, PHP, MySQL et d’autres.')?></p>
                <br>
                <p><?= __('Je suis disponible immédiatement pour échanger avec vous alors n\'hésitez pas à me contacter !')?></p>
            </article>
        </section>
        
        <section class="d-flex contact-resume">
            <a href="ressources/CV_Luna_09122024.pdf" download="CV de Luna BURATTI-FAYOLLE.pdf" class="resume">Télécharger mon CV (FR)</a>
            <a href="ressources/Luna_Resume_09122024.pdf" download="Luna BURATTI-FAYOLLE's Resume.pdf" class="resume">Download my Resume (EN)</a>
        </section>
            
        <hr>
        
        <div class="d-flex title-projects">
            <h1 id="projects"><?= __('Projets')?></h1>
        </div>
        <section>
	        <article class="d-flex parent-project">
                <article class="project">
                    <a href="https://github.com/Luna-bf/To-do_list_JavaScript" target="_blank">
                        <img src="imgs/projects/todo-list_thumbnail.png" alt=<?= __('"Capture d\'écran de la To-do list Javascript"')?> class="project-img" />
                    </a>
                    <ul>
                        <li><?= __('Année : 2024 (en cours)')?></li>
                        <li><?= __('Stacks utilisées :') ?> JavaScript, HTML <?= __('et')?> CSS</li>
                        <li><a href="https://github.com/Luna-bf/To-do_list_JavaScript" target="_blank" class="github-link"><?= __('Lien Github')?></a></li>
                    </ul>
                </article>
            
                <article class="project">
                    <a href="https://github.com/Luna-bf/Hollow_Knight-Quiz" target="_blank">
                        <img src="imgs/projects/hk-quiz_thumbnail.png" alt=<?= __('"Capture d\'écran du quiz Hollow Knight"')?> class="project-img" />
                    </a>
                    <ul>
                        <li><?= __('Année : 2024 (en cours)')?></li>
                        <li><?= __('Stacks utilisées :') ?> JavaScript, HTML <?= __('et')?> CSS</li>
                        <li><a href="https://github.com/Luna-bf/Hollow_Knight-Quiz" target="_blank" class="github-link"><?= __('Lien Github')?></a></li>
                    </ul>
                </article>
            
                <article class="project">
                    <a href="https://github.com/Luna-bf/PHP-RPG" target="_blank">
                        <img src="imgs/projects/php-rpg_thumbnail.png" alt=<?= __('"Capture d\'écran du RPG PHP"')?> class="project-img" />
                    </a>
                    <ul>
                        <li><?= __('Année : 2024 (en cours)')?></li>
                        <li><?= __('Stacks utilisées :') ?> PHP, HTML <?= __('et')?> CSS</li>
                        <li><a href="https://github.com/Luna-bf/PHP-RPG" target="_blank" class="github-link"><?= __('Lien Github')?></a></li>
                    </ul>
                </article>
                
            </article>
        </section>
        
        <hr>
        
        <div class="d-flex title-competences">
            <h1 id="competences" class="d-flex"><?= __('Compétences')?></h1>
        </div>
        
        <section class="section-padding">
            <div class="d-flex parent">
                <h2 class="d-flex title-lang"><?= __('Langues')?></h2>
                <article id="langues">    
                    <ul class="d-flex">
                        <li><?= __('Français : Langue maternelle')?></li>
                        <li><?= __('Anglais : niveau B1')?></li>
                    </ul>
                </article>
                
                <hr class="skills-hr">
                
                <h2 class="d-flex title-soft-skills">Soft Skills</h2>
                <article class="soft-skills">
                        <ul>
                            <li><?= __('Prise de recul : Je suis ouverte à la critique et à la conversation')?></li>
                            <li><?= __('Curiosité : Je suis ouverte à de nouveaux outils et langages')?></li>
                            <li><?= __('Persévérance : Je n\'abandonne pas face à la difficulté')?></li>
                        </ul>
                </article>
                
                <hr class="skills-hr">
                
                <h2 class="d-flex title-hard-skills">Hard skills (front-end)</h2>
                <article class="hard-skills-front-article-1">
                    <div id="html">
                        <a href="https://fr.wikipedia.org/wiki/Hypertext_Markup_Language" target="_blank"><img src="imgs/logos/HTML_logo.png" alt="Logo HTML" /></a>
                        <h3>HTML</h3>
                    </div>
                    
                    <div id="css">
                        <a href="https://fr.wikipedia.org/wiki/Feuilles_de_style_en_cascade" target="_blank"><img src="imgs/logos/CSS-logo.png" alt="Logo CSS" /></a>
                        <h3>CSS</h3>
                    </div>
                    
                    <div id="js">
                        <a href="https://fr.wikipedia.org/wiki/JavaScript" target="_blank"><img src="imgs/logos/JavaScript_logo.png" alt="Logo JavaScript" /></a>
                        <h3>JavaScript</h3>
                    </div>
                </article>
                
                <article class="hard-skills-front-article-2">
                    <div id="figma">
                        <a href="https://fr.wikipedia.org/wiki/Figma" target="_blank"><img src="imgs/logos/Figma_logo.png" alt="Logo Figma" /></a>
                        <h3>Figma</h3>
                    </div>
                    
                    <div id="swift">
                        <a href="https://fr.wikipedia.org/wiki/Swift_(langage_d%27Apple)" target="_blank"><img src="imgs/logos/Swift_logo.png" alt="Logo Swift" /></a>
                        <h3>Swift</h3>
                    </div>
                    
                    <div id="swift-ui">
                        <a href="https://en.wikipedia.org/wiki/SwiftUI" target="_blank"><img src="imgs/logos/SwiftUI_logo.png" alt="Logo SwiftUI" /></a>
                        <h3>SwiftUI</h3>
                    </div>
                </article>
                
                <hr id="hard-skills-hr">
                
                <h2 class="d-flex title-hard-skills">Hard skills (back-end)</h2>
                <article class="hard-skills-back-article">
                    <div class="logos-backend">
                        <img src="imgs/logos/logos_back-end.png" alt=<?= __('"Logos des langages et outils que j\'utilise en back-end"')?>>
                    </div>
                </article>
            </div>
        </section>
        
        <hr>
        
        <div class="d-flex title-contact">
            <h1 id="contact"><?= __('Contactez moi')?></h1>
        </div>
        
        <section id="contact-me">
            <form action="form/form.php" method="POST">
                <div class="d-flex" id="form-group">
                    <input type="text" id="companyName" name="companyName" placeholder=<?= __('"Nom de l\'entreprise (obligatoire)"')?> tabindex="1" required>
                    <input type="email" id="email" name="userEmail" placeholder=<?= __('"Votre adresse mail (obligatoire)"')?> tabindex="2" required>
                    <input type="text" id="subject" name="subject" placeholder=<?= __('"Objet (obligatoire)"')?> tabindex="3" required>
                    <textarea id="message" name="message" placeholder=<?= __('"Votre message"')?> tabindex="4"></textarea>
					<button type="submit" id="submit-button"><?= __('Soumettre')?></button>
                </div>
            </form>
        </section>
    </main>
    
    <footer id="footer">
        <ul class="contacts">
            <li><?= __('Contact 3W Academy :') ?></li>
            <li>Jérémy Rocamora : jr.rocamora@gmail.com</li>
        </ul>
        
        <ul class="contacts">
            <li><?= __('Mon adresse mail :') ?></li>
            <li>lburattifayolle@gmail.com</li>
        </ul>
    </footer>
        
    <a href="#" id="return-to-top">
        <i class="fa-solid fa-arrow-up"></i>
    </a>
    
    <div id="prompt" class="hide-prompt">
        <button><i class="fa-solid fa-circle-xmark"></i></button>
        <div id="prompt-text">
            <p class="prompt-first-p"><?= __('Bonjour/bonsoir,') ?></p>
            <p class="prompt-p"><?= __('Cette boîte de texte est apparue pour vous prévenir que le formulaire de contact ne fonctionne actuellement pas.') ?></p>
            <p class="prompt-p"><?= __('Je vous invite à utiliser mon adresse mail présente dans') ?> <a href="#footer" id="footer-link"><?= __('le footer') ?></a> <?= __('pour me contacter.') ?></p>
            <p class="prompt-p"><?= __('Je vous remercie pour votre temps et votre compréhension et vous souhaite de passer une excellente journée/soirée.') ?></p>
            <p class="prompt-polite"><?= __('Cordialement,') ?></p>
            <p class="prompt-final-p">Luna BURATTI-FAYOLLE</p>
        </div>
    </div>
    
    <script type="text/javascript" src="js/app.js" defer></script>
</body>
</html>
