<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="author" content="Luna BURATTI-FAYOLLE">
    <title>Portfolio - Luna BURATTI-FAYOLLE</title>
    <link rel="stylesheet" href="css/style.css" type="text/css" >
    <link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css" type="text/css" >
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <link rel="icon" type="image/x-icon" href="imgs/favicon-48x48.png" />
</head>
<body>
    <nav>
        <ul class="d-flex">
            <li><a href="#accueil">Accueil</a></li>
            <li><a href="#competences">Compétences</a></li>
            <li><a href="#formations">Formations</a></li>
            <li><a href="#projects">Projets</a></li>
            <li><a href="#contact-me">Contact</a></li>
        </ul>
    </nav>
    
    <header class="d-flex" id="header">
        <h1>Bonjour, je m’appelle <span>Luna</span> et je suis une jeune <span>développeuse web junior</span> de 19 ans.</h1>
        <h2>Je recherche activement une <span>alternance</span> pour devenir une développeuse full stack confirmée.</h2>
    </header>
    
    <main class="container" id="accueil">
        
        <a href="js/app.js" id="return-to-top"><i class="icon-chevron-up"></i></a>
        
        <section class="home d-flex">
            
            <div class="d-flex profile">
                <img src="imgs/Photo_CV_30092024.jpg" class="profile-img" alt="Ma photo">
    
                <p class="find-me">Vous pouvez me retrouver sur :</p>
                <article class="d-flex socials-icons">
                    <a href="https://github.com/Luna-bf" target="_blank" class="fa-brands fa-github"></a>
                    <a href="https://www.linkedin.com/in/luna-buratti-fayolle-491062310/" target="_blank" class="fa-brands fa-linkedin"></a>
                </article>
            </div>
            
            <article class="searching-for">
                <p>Actuellement en recherche à la 3W Academy, je suis une jeune développeuse web junior de 19 ans passionnée par le développement et la création de solutions innovantes. Dans l’optique d’évoluer dans ce domaine, je suis en quête d'une opportunité d’apprentissage en alternance pour mettre en pratique mes compétences et apprendre auprès de professionnels expérimentés.</p>
                <br>
                <p>Motivation, curiosité et persévérance sont des soft skills qui me représentent et bien que je sois au début de mon parcours, je suis déterminée à monter en compétences aussi bien front-end qu’en back-end afin de devenir une développeuse full-stack confirmée. Je possède déjà des connaissances en HTML, CSS, PHP, MySQL et d’autres.</p>
                <br>
                <p>Je suis à la recherche d'une entreprise prête à signer un contrat d’apprentissage pour une durée de 12 mois avec le rythme suivant : 1 semaine à l'école et 3 semaines en entreprise.</p>
                <br>
                <p>Je suis disponible immédiatement pour échanger avec vous alors n’hésitez pas à me contacter !</p>
            </article>
        </section>
        
        <section class="d-flex contact-resume">
            <!--<a href="#contact-me" class="contact-me-link">Me contacter</a>-->
            <a href="ressources/CV_Luna_16102024.pdf" download="CV de Luna BURATTI-FAYOLLE.pdf" class="resume">Télécharger mon CV (FR)</a>
            <a href="ressources/Luna_Resume_16102024.pdf" download="Luna BURATTI-FAYOLLE's Resume.pdf" class="resume">Download my Resume (EN)</a>
        </section>
        
        <section>
            <div class="d-flex title-competences">
                <h1 id="competences">Compétences</h1>
            </div>
            
            <div class="left animation-item slide-right">
                <article class="d-flex parent-languages slide-in from-right">
                    <article class="languages">
                        <h2 class="d-flex title">Langues</h2>
                        <ul>
                            <li>Français : Langue maternelle</li>
                            <li>Anglais : niveau B1</li>
                        </ul>
                    </article>
                    <div class="icon-languages">
                        <img src="imgs/icons/languages_icon.png" alt="Icône de l'article langues">
                    </div>
                </article>
            </div>
            
            <div class="right animation-item slide-left">
                <article class="d-flex parent-soft-skills slide-in from-left">
                    <div class="icon-soft-skills">
                        <img src="imgs/icons/soft_skills_icon.png" alt="Icône de l'article soft skills">
                    </div>
                    <article class="soft-skills">
                        <h2 class="d-flex title">Soft Skills</h2>
                        <ul>
                            <li>Prise de recul : Je suis ouverte à la critique et à la conversation.</li>
                            <li>Curiosité : Je suis ouverte à des nouvelles choses.</li>
                            <li>Persévérance : Je fais toujours de mon mieux et je n'abandonne pas devant la difficulté.</li>
                        </ul>
                    </article>
                </article>
            </div>
            
            <div class="left animation-item slide-right">
                <article class="d-flex parent-hard-skills-front slide-in from-right">
                    <article class="hard-skills-front">
                        <h2 class="d-flex title">Hard skills (frontend)</h2>
                        <img class="logos-frontend" src="imgs/logos/logos_frontend.png" alt="Logo des langages et outils que j'utilise en frontend">
                    </article>
                    <div class="icon-hard-skills-front">
                        <img src="imgs/icons/front_end_icon.png" alt="Icône de l'article hard skills (frontend)">
                    </div>
                </article>
            </div>
            
            <div class="right animation-item slide-left">
                <article class="d-flex parent-hard-skills-back slide-in from-left">
                    <div class="icon-hard-skills-back">
                        <img src="imgs/icons/back_end_icon.png" alt="Icône de l'article hard skills (backend)">
                    </div>
                    <article class="d-flex hard-skills-back">
                        <h2 class="d-flex title">Hard skills (backend)</h2>
                        <img class="logos-backend" src="imgs/logos/logos_backend.png" alt="Logo des langages et outils que j'utilise en backend">
                    </article>
                </article>
            </div>
        </section>
        
        <section>
            <div class="d-flex title-formations">
                <h1 id="formations" class="d-flex">Formations</h1>
            </div>
            <article class="d-flex parent-booster">
                <article class="booster-live100">
                    <h2 class="booster-h2-title">Booster Live100 - 2024</h2>
                    <h3 class="booster-h3-title">3W Academy</h3>
                    <ul>
                        <li>Apprendre l’intégration avec 4 langages de développement web : HTML, CSS, JavaScript et PHP.</li>
                        <li>Découvrir les différents outils utilisés en développement full stack : Bootstrap (librairie), Vue.js (framework), MySQL (gestion de bases de données), le MCD, la POO et l’architecture MVC (Model View Controller)</li>
                    </ul>
                    <img class="logos-booster" src="imgs/logos/logos_booster.png" alt="Logo des langages et outils utilisés pendant cette formation">
                </article>
            </article>
            
            <article class="d-flex parent-booster">
                <article class="apple-foundation-program">
                    <h2 class="apple-foundation-program-h2-title">Apple Foundation Program - 2024</h2>
                    <h3 class="apple-foundation-program-h3-title">Simplon.co</h3>
                    <ul>
                        <li>Concevoir une application mobile à partir d’une problématique</li>
                        <li>Développer une application mobile iOS</li>
                        <li>Développer des compétences transversales qui renforcent l’employabilité</li>
                    </ul>
                <div class="d-flex parent-logo-100">
                    <img class="logos-afp" src="imgs/logos/logos_afp.png" alt="Logo des langages et outils utilisés pendant cette formation">
                </div>
                </article>
            </article>
        </section>
        
        <section>
            <div class="d-flex title-experiences">
                <h1 id="experiences">Expériences</h1>
            </div>
            <article class="d-flex parent-ada">
                <article class="adatech-school">
                    <h2 class="adatech-school-h2-title">Stage de découverte - 2023</h2>
                    <h3 class="adatech-school-h3-title">AdaTech School</h3>
                    <ul>
                        <li>Découvrir le développement web</li>
                        <li>Découvrir et prendre en main les langages suivants : HTML et CSS</li>
                    </ul>
                    <img class="logos-adatech-school" src="imgs/logos/logos_adatech_school.png" alt="Logo des langages utilisés pendant ce stage">
                </article>
            </article>
        </section>
        
        <section>
            <div class="d-flex title-projects">
                <h1 id="projects">Projets</h1>
            </div>
	        <article class="d-flex parent-project">
                <article class="project">
                    <img src="imgs/projects/hk-quiz_thumbnail.png" alt="Capture d'écran du quiz Hollow Knight" class="project-img" />
                    <ul>
                        <li>Année : 2024 (en cours)</li>
                        <li>Technos utilisées : JavaScript, HTML, CSS</li>
                        <li><a href="https://github.com/Luna-bf/Hollow_Knight-Quiz" target="_blank">Lien Github</a></li>
                    </ul>
                </article>
            </article>
	
            <article class="d-flex parent-project">
                <article class="project project-mb">
                    <img src="imgs/projects/php-rpg_thumbnail.png" alt="Capture d'écran du RPG PHP" class="project-img" />
                    <ul>
                        <li>Année : 2024 (en cours)</li>
                        <li>Technos utilisées : PHP, HTML, CSS</li>
                        <li><a href="https://github.com/Luna-bf/PHP-RPG" target="_blank">Lien Github</a></li>
                    </ul>
                </article>
            </article>
        </section>
        
        <section id="contact-me">
            <div class="d-flex title-contact">
                <h1 id="contact">Contactez moi</h1>
            </div>
            <form method="POST">
                <div class="d-flex">
                    <div class="my-form">
                        <input type="text" id="company_name" name="company_name" placeholder="Nom de l'entreprise (obligatoire)" required>
                        <input type="email" id="email" name="email" placeholder="Votre adresse mail (obligatoire)" required>
                        <textarea id="message" name="message" placeholder="Votre message"></textarea>
					    <button type="submit" class="button">Envoyer</button>
                    </div>
                </div>
            </form>
        </section>
    </main>
    
    <footer>
        <p>Luna BURATTI-FAYOLLE - 2024</p>
        <p>Tous droits réservés</p>
    </footer>
    
    <!--<script type="text/javascript" src="js/app.js"></script>-->
</body>
</html>
